version: '3'
services:
  web:
    image: odoo:13.0
    restart: always
    depends_on:
      - mydb
    ports:
      - "8070:8069"
    environment:
    - HOST=mydb
    - USER=odoo
    - PASSWORD=admin
  mydb:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=admin
